services:
  coup-backend:
    build: ./coup-server
    container_name: coup_backend
    ports:
      - '8080:8080'
    restart: always
  coup-frontend:
    build: ./coup-client
    container_name: coup_frontend
    ports:
      - '3000:3000'
    restart: always
    environment:
      NEXT_PUBLIC_WEBSOCKET_URL: ws://app:8080/room-websocket
    depends_on:
      - coup-backend