services:
  app:
    build: coup-server
    container_name: app_coup
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_coup
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always
volumes:
  redis_data: