services:
  coup-backend:
    build: ./coup-server
    container_name: coup_backend
    ports:
      - '8080:8080'
    restart: always
  coup-frontend:
    build: ./coup-client
    container_name: coup_frontend
    ports:
      - '3000:3000'
    restart: always
    environment:
      # Permite que o frontend se conecte ao backend
      NEXT_PUBLIC_WEBSOCKET_URL: ws://app:8080/room-websocket
    depends_on:
      - coup-backend
#    depends_on:
#      - redis
#  redis:
#    image: redis:latest
#    container_name: redis_coup
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis_data:/data
#    restart: always
#volumes:
#  redis_data: