package com.estudos.coup.model

enum class TurnState {
    AWAITING_ACTION,
    AWAITING_CHALLENGE_OR_COUNTER_ACTION,
    ACTION_FINALIZED,
    CHALLENGED,
    CHALLENGE_WIN,
    CHALLENGE_LOSE,
    COUNTER_ACTION,
    COUNTER_ACTION_ACCEPTED,
    COUNTER_ACTION_CHALLENGED,
    COUNTER_ACTION_CHALLENGE_WIN,
    COUNTER_ACTION_CHALLENGE_LOSE
}
